pos/myapp/urls.py
from django.urls import path
from .views import *
from . import views
app_name = 'myapp'
urlpatterns = [
    path('test',views.test, name='test'),
    path('HomeView', HomeView.as_view(), name='HomeView'),
    path('ProductCreate', ProductCreate.as_view(), name='ProductCreate'),
    path('ProductEditView/<int:pk>/', ProductEditView.as_view(), name='ProductEditView'),
    path('CategoryCreate',CategoryCreate.as_view(), name='CategoryCreate'),
    path('login', UserLoginView.as_view(), name = 'UserLoginView'),
    path('logout/', UserLogoutView.as_view(), name='UserLogoutView'),
    path('AddToCartView/<int:pro_id>', AddToCartView.as_view(), name='AddToCartView'),
    path('mycart/', MyCartView.as_view(), name='MyCartView'),
    path('manage/<int:cp_id>/', ManageCartView.as_view(), name='ManageCartView'),
    path('checkout/', CheckoutView.as_view(), name='CheckoutView'),
    path('empty/', EmptyCartView.as_view(), name='EmptyCartView'),

    path('SupplierCreate/', SupplierCreate.as_view(), name='SupplierCreate'),
    path('SupplierEdit/<int:pk>/', SupplierEdit.as_view(), name='SupplierEdit'),
    path('PurchaseCreateView/<int:id>/', PurchaseCreateView.as_view(), name='PurchaseCreateView'),
    path('PurchaseData/', PurchaseData.as_view(), name='PurchaseData'),
    path('PurchaseReport/', PurchaseReport.as_view(), name='PurchaseReport'),
    path('PurchaseDataDelete/<int:pk>/', PurchaseDataDelete.as_view(), name='PurchaseDataDelete'),

    path('SaleInvoiceView/', SaleInvoiceView.as_view(), name='SaleInvoiceView'),
    path('SaleInvoiceReportFilter/', SaleInvoiceReportFilter.as_view(), name='SaleInvoiceReportFilter'),
    path('InvoiceDetailView/<int:pk>/', InvoiceDetailView.as_view(), name='InvoiceDetailView'),
    path('InvoiceStatusChange/<int:pk>/', InvoiceStatusChange.as_view(), name='InvoiceStatusChange'),
    path('SaleItemReportView', SaleItemReportView.as_view(), name='SaleItemReportView'),
    path('GPView', GPView.as_view(), name='GPView'),
    path('Deliverpayment/<int:pk>', Deliverpayment.as_view(), name='Deliverpayment'),
    path('DeliveryPaymentReportView/', DeliveryPaymentReportView, name='DeliveryPaymentReportView'),
    path('InvoiceThermalPrintView/<int:pk>/', InvoiceThermalPrintView.as_view(), name='InvoiceThermalPrintView'),

    path('DamageItemView/', DamageItemView.as_view(), name='DamageItemView'),
    path('DamageInvoiceView/<int:id>/', DamageInvoiceView.as_view(), name='DamageInvoiceView'),
    path('DamageProductView/<int:id>/', DamageProductView.as_view(), name='DamageProductView'),
    path('DamageReportView/', DamageReportView.as_view(), name='DamageReportView'),

    path('ExpenseLedgerView/<int:id>', ExpenseLedgerView.as_view(), name='ExpenseLedgerView'),
    path('LedgerImport/', LedgerImport.as_view(), name='LedgerImport'),
    path('ExpenseReportView/', ExpenseReportView.as_view(), name='ExpenseReportView'),
    path('ExpenseReportFilter/', ExpenseReportFilter.as_view(), name='ExpenseReportFilter'),
    path('LedgerCreateView/', LedgerCreateView.as_view(), name='LedgerCreateView'),

    path('', DashboardView.as_view(), name='DashboardView'),
    # path('DashboardReportView/', DashboardReportView, name='DashboardReportView'),
    path('testbarcode/', testbarcode.as_view(), name='testbarcode'),
    path('DeliveryView', DeliveryView.as_view(), name= 'DeliveryView'),
    path('pdf_invoice_create/<int:id>/', pdf_invoice_create, name='pdf_invoice_create'),


]

pos/pos/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Test(models.Model):
    name = models.CharField(max_length=225)

    def __str__(self):
        return self.name

class Supplier(models.Model):
    supplier_name = models.CharField(max_length=225)
    phone_number = models.CharField(max_length=225)
    address = models.CharField(max_length=225)

    def __del__(self):
        return self.supplier_name

class Category(models.Model):
    category_name = models.CharField(max_length=225)

    def __str__(self):
        return self.category_name

class Items(models.Model):
    item_name = models.CharField(max_length=225)
    category = models.CharField(max_length=225)
    pruchase_price = models.FloatField(default=0.00)
    sell_price = models.FloatField(default=0.00)
    wholesale_price = models.FloatField(default=0.00)
    balance_qty = models.IntegerField(default=0)
    barcode_id = models.CharField(max_length=225,blank=True, null=True)
    photo = models.ImageField(upload_to='', blank=True, null=True)


    def __str__(self):
        return self.item_name

class Cart(models.Model):
    staff = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    tax = models.PositiveIntegerField(default=0)
    super_total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Items, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    remain_balance = models.IntegerField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Cart : "+ str(self.cart.id)+ "CartProduct : " + str(self.id)

STATUS=(
    ("Ordering","Ordering"),("Delivered","Delivered"),("Cash","Cash"),("Credit","Credit"),("Consignment","Consignment"),("Complete","Complete")
)

PAYMENT_TYPE = (
    ("Cash","Cash"),
("COD","COD"),
("Kpay","Kpay"),
("WavePay","WavePay"),
)

class DeliverySystem(models.Model):
    delivery_name = models.CharField(max_length=225)

    def __str__(self):
        return self.delivery_name

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=255,null=True, blank=True)
    shipping_address = models.CharField(max_length=255, null=True, blank=True)
    mobile = models.CharField(max_length=255,null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField(default=0)
    total = models.PositiveIntegerField()
    tax = models.PositiveIntegerField()
    delivery_fee = models.IntegerField(default=0)
    delivery_system = models.ForeignKey(DeliverySystem, on_delete=models.CASCADE, blank=True,null=True)
    all_total = models.PositiveIntegerField()
    all_total_delivery = models.IntegerField(default=0)
    ordered_staus = models.CharField(max_length=255, choices=STATUS, default='Cash')
    payment = models.CharField(max_length=225, choices=PAYMENT_TYPE, default='Cash')
    deli_payment = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Order : " + str(self.id)


class PurchaseList(models.Model):
    supplier_name = models.CharField(max_length=225)
    item_name = models.CharField(max_length=225)
    purchase_qty = models.IntegerField(default=0)
    purchase_price = models.IntegerField(default=0)
    sale_price = models.IntegerField(default=0)
    logistic = models.IntegerField(default=0)
    total_purchase_price = models.IntegerField(default=0)
    p_date = models.DateField()
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.item_name

class DamageItems(models.Model):
    item_name = models.CharField(max_length=225)
    category = models.CharField(max_length=225,blank=True,null=True)
    item_code = models.CharField(max_length=225,blank=True,null=True)
    quantity = models.IntegerField(default=0)
    return_delivery_charge = models.IntegerField(default=0)
    description = models.CharField(max_length=225,blank=True,null=True)
    return_date = models.DateField()
    created_at = models.DateField(auto_now_add=True)

class ExpenseLedger(models.Model):
    category = models.CharField(max_length=225,unique=True)
    balance = models.IntegerField(default=0)

class ExpenseReport(models.Model):
    expense_type = models.CharField(max_length=225)
    title = models.CharField(max_length=225)
    category = models.CharField(max_length=225)
    amount = models.IntegerField(default=0)
    expense_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)

pos/templates/damage_invoice_view.html
{% extends 'base.html' %}

{% block content %}

<!--===================================-->
            {% if message %}

            <div class="alert alert-danger" role="alert">
                <a href="{{current_path}}" class="text-danger">{{message}}</a>

            </div>

            {% endif %}



<!--=============================================================-->
<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Items List</h4>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-warning">
                <th>ID</th>
                <th class="text-center">ordered_by</th>
                <th class="text-center">all_total</th>
                <th class="text-center">Action</th>




            </tr>
            </thead>
            <tbody>
            {% for p in invoice %}
            <tr class="table-info">
                <td class="table-plus"><b>{{p.id}}</b></td>
                 <td><b>{{p.ordered_by}}</b></td>
                <td><b>{{p.all_total}}</b></td>
                <td><a href="{% url 'myapp:DamageInvoiceView' p.id%}" class="btn btn-sm btn-danger"><i class="micon bi bi-recycle"></i>Return</a></td>

            </tr>
            {% endfor %}

            </tbody>

        </table>
    </div>
</div>
<!--##############################################-->


{% endblock content %}

pos/templates/damage_report.html
{% extends 'base.html' %}

{% block content %}

<!--===================================-->
            {% if message %}

            <div class="alert alert-danger" role="alert">
                <a href="{{current_path}}" class="text-danger">{{message}}</a>

            </div>

            {% endif %}



<!--=============================================================-->


<!-- Bootstrap Select Start -->
					<div class="pd-20 card-box mb-30">
						<div class="clearfix">
							<div class="pull-left">
								<h4 class="text-blue h4">Filter Report</h4>

							</div>
						</div>
						<form action="{% url 'myapp:DamageReportView' %}" method="post">{% csrf_token %}
							<div class="row">
								<div class="col-md-4 col-sm-12">
									<div class="form-group">
										<label>From Date</label>
                                        <input type="date" name="fromdate" class="form-control">
									</div>
								</div>
                                <div class="col-md-4 col-sm-12">
									<div class="form-group">
										<label>To Date</label>
                                        <input type="date" name="todate" class="form-control">
									</div>
								</div>

							</div>
                            <button
										type="submit"
										class="btn btn-sm"
										data-bgcolor="#00b489"
										data-color="#ffffff"
									>
                                <i class="icon-copy dw dw-filter-1"></i>Filter Report

									</button>

						</form>
					</div>
					<!-- Bootstrap Select End -->

<!-- Export Datatable start -->
<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Damage List</h4>
    </div>
    <div class="pb-20">
        <table
                class="table hover multiple-select-row data-table-export nowrap"
        >
            <thead>
            <tr class="table-warning">

                <th class="">Item Name</th>
                <th class="">Quantity</th>
                <th class=""> Date</th>
                <th class="">Description</th>
<!--                <th class="">Date</th>-->


            </tr>
            </thead>
            <tbody>
            {% for p in damage_rp %}
            <tr class="table-info">
                <td class="table-plus"><b>{{p.item_name}}</b></td>
                 <td><b>{{p.quantity}}</b></td>
                <td><b>{{p.return_date}}</b></td>
                <td><b>{{p.description}}</b></td>
<!--                <td><b>{{p.expense_date}}</b></td>-->

            </tr>
            {% endfor %}


            </tbody>
            <tfoot>
            <tr>
                <td></td>
                <td></td>
                <th class="text-danger"></th>
                <th class="text-danger"></th>
                <td></td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>
<!-- Export Datatable End -->

{% endblock content %}

pos/templates/invoice_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Helll PDF</h1>
</body>
</html>

pos/templates/ledgercreate.html
{% extends 'base.html' %}

{% block content %}

<!--===================================-->
            {% if message %}

            <div class="alert alert-danger" role="alert">
                <a href="{{current_path}}" class="text-danger">{{message}}</a>

            </div>

            {% endif %}

<!--=======================-->


<div class="page-header">
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h4 class="text-primary">Create Ledger</h4>

            </div>
            <hr>

        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <form action="{% url 'myapp:LedgerCreateView' %}" method="post">{% csrf_token %}

                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Expense Title</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="category">
                    </div>
                </div>


                <input type="submit" value="Create Expense" class="btn btn-outline-success">


            </form>
        </div>
    </div>
</div>


{% endblock content %}

pos/templates/productcreate.html
{% extends 'base.html' %}

{% block content %}

<!--<div class="page-header">-->
<!--    <div class="row">-->
<!--        <div class="col-md-6 col-sm-12">-->
<!--            <div class="title">-->
<!--                <h5>Create New Product</h5>-->

<!--            </div>-->
<!--            <hr>-->
<!--            {% if message %}-->
<!--            <div class="alert alert-danger" role="alert">-->
<!--                {{message}}-->
<!--            </div>-->
<!--            {% endif %}-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="row">-->
<!--        <div class="col-md-6 col-sm-12">-->
<!--            <form action="{% url 'myapp:ProductCreate' %}" method="post">{% csrf_token %}-->
<!--                <div class="form-group row">-->
<!--                    <label class="col-sm-12 col-md-2 col-form-label">Item Name</label>-->
<!--                    <div class="col-sm-12 col-md-10">-->
<!--                        <input class="form-control" type="text" placeholder="" name="item_name">-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="form-group row">-->
<!--                    <label class="col-sm-12 col-md-2 col-form-label">Category</label>-->
<!--                    <div class="col-sm-12 col-md-10">-->
<!--                        <select class="custom-select col-12" name="category">-->
<!--                            <option selected="">Select Category Name</option>-->
<!--                            {% for c in category %}-->
<!--                            <option>{{c.category_name}}</option>-->
<!--                            {% endfor %}-->

<!--                        </select>-->
<!--                    </div>-->

<!--                </div>-->

<!--                <div class="form-group row">-->
<!--                    <label class="col-sm-12 col-md-2 col-form-label">Purchase Price</label>-->
<!--                    <div class="col-sm-12 col-md-10">-->
<!--                        <input class="form-control" type="number" placeholder="" name="purchase_price">-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="form-group row">-->
<!--                    <label class="col-sm-12 col-md-2 col-form-label">Sale Price</label>-->
<!--                    <div class="col-sm-12 col-md-10">-->
<!--                        <input class="form-control" type="number" placeholder="" name="sale_price">-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="form-group row">-->
<!--                    <label class="col-sm-12 col-md-2 col-form-label">BarCode</label>-->
<!--                    <div class="col-sm-12 col-md-10">-->
<!--                        <input class="form-control" type="number" placeholder="" value="0" name="barcode_id">-->
<!--                    </div>-->
<!--                </div>-->


<!--                <input type="submit" value="CreateProduct" class="btn btn-outline-primary">-->


<!--            </form>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

{% if message %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {% endif %}


<h4 class="text-blue h4">Item List</h4>
<!--=============================================================-->
<div class="card-box mb-30">
    <div class="pd-20">
<!--        <h4 class="text-blue h4">Item List</h4>-->
        <a
									href="#"
									class="btn btn-sm btn-outline-primary"
									data-toggle="modal"
									data-target="#Medium-modal"
									type="button"
								>
									+ Add Item Name
								</a>
								<div
									class="modal fade"
									id="Medium-modal"
									tabindex="-1"
									role="dialog"
									aria-labelledby="myLargeModalLabel"
									aria-hidden="true"
								>
									<div class="modal-dialog modal-dialog-centered">
                                        <form action="{% url 'myapp:ProductCreate' %}" method="post">{% csrf_token %}
										<div class="modal-content">
											<div class="modal-header">
												<h4 class="modal-title" id="myLargeModalLabel">
													New Item
												</h4>
												<button
													type="button"
													class="close"
													data-dismiss="modal"
													aria-hidden="true"
												>
													×
												</button>
											</div>

											<div class="modal-body">
												<div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Item Name</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="item_name">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Category</label>
                    <div class="col-sm-12 col-md-10">
                        <select class="custom-select col-12" name="category">
                            <option selected="">Select Category Name</option>
                            {% for c in category %}
                            <option>{{c.category_name}}</option>
                            {% endfor %}

                        </select>
                    </div>

                </div>

                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Purchase Price</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="number" placeholder="" name="purchase_price">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Sale Price</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="number" placeholder="" name="sale_price">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">BarCode</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" value="0" name="barcode_id">
                    </div>
                </div>
											</div>
											<div class="modal-footer">
												<button
													type="button"
													class="btn btn-secondary"
													data-dismiss="modal"
												>
													Close
												</button>
												<button type="submit" class="btn btn-primary">
													Save Item Name
												</button>
											</div>
										</div>
                                            </form>
									</div>
								</div>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-warning">

                <th>Name</th>
                <th>Category</th>
                <th>PurchasePrice</th>
                <th>SalePrice</th>
                <th>BalanceQTY</th>

            </tr>
            </thead>
            <tbody>
            {% for p in item_list %}
            <tr class="table-info">
                <td class="table-plus"><a href="{% url 'myapp:ProductEditView' p.id %}"><b>{{p.item_name}}</b></a></td>
                <td>{{p.category}}</td>
                <td>{{p.pruchase_price}}</td>
                <td>{{p.sell_price}}</td>
                <td>{{p.balance_qty}}</td>


            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

pos/templates/productedit.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header">
    <div class="row">
        <div class="col-md-12 col-sm-12">

            <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
                {{form}}
                <hr>
                <input type="submit" class="btn btn-primary" value="Save Product">
            </form>


        </div>

    </div>
</div>


{% endblock content %}

pos/templates/purchasedata.html
{% extends 'base.html' %}

{% block content %}


<!--=============================================================-->
{% if message %}
<div class="alert alert-danger" role="alert">
    {{message}}
</div>
{% endif %}
{% if success %}
<div class="alert alert-success" role="alert">
    {{success}}
</div>
{% endif %}

<div class="card-box mb-30">
    <div class="pd-20">
        <!--        <h4 class="text-blue h4">Supplier List</h4>-->

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr>

                <th class="text-primary">Supplier Name</th>
                <th class="text-primary">Address</th>
                <th class="text-primary">Create</th>


            </tr>
            </thead>
            <tbody>
            {% for p in supplier %}
            <tr>

                <td class="table-plus"><b>{{p.supplier_name}}</b></td>
                <td>{{p.address}}</td>
                <td><a href="{% url 'myapp:PurchaseCreateView' p.id%}" class="btn btn-sm btn-primary"><i class="icon-copy dw dw-edit1"></i>Purchase
                    Invoice</a></td>


            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

<hr>

<!-- Bootstrap Select Start -->
					<div class="pd-20 card-box mb-30">
						<div class="clearfix">
							<div class="pull-left">
								<h4 class="text-blue h4">Filter Report</h4>

							</div>
						</div>
						<form action="{% url 'myapp:PurchaseReport' %}" method="post">{% csrf_token %}
							<div class="row">
								<div class="col-md-4 col-sm-12">
									<div class="form-group">
										<label>From Date</label>
                                        <input type="date" name="fromdate" class="form-control">
									</div>
								</div>
                                <div class="col-md-4 col-sm-12">
									<div class="form-group">
										<label>To Date</label>
                                        <input type="date" name="todate" class="form-control">
									</div>
								</div>

							</div>
                            <button
										type="submit"
										class="btn btn-sm"
										data-bgcolor="#00b489"
										data-color="#ffffff"
									>
                                <i class="icon-copy dw dw-filter-1"></i>Filter Report

									</button>

						</form>
					</div>
					<!-- Bootstrap Select End -->
<!-- Export Datatable start -->
<div class="card-box mb-30">

    <div class="pd-20">
        <h4 class="text-blue h4">Purchase Invoice Report</h4>

    </div>
    <div class="pb-20">
        <table
                class="table hover data-table-export nowrap"
        >
            <thead>
            <tr class="table-info">
                <th>Date</th>
                <th class="text-center">Supplier Name</th>
                <th class="text-center">Items</th>
                <th class="text-center">Qty</th>
                <th>Purchase Price</th>
                <th>Logistic</th>
                <th>Total</th>
                <th>Action</th>


            </tr>
            </thead>
            <tbody>
            {% for p in purchasedata %}
            <tr class="">
                <td>{{p.p_date}}</td>
                <td class="table-plus"><b>{{p.supplier_name}}</b></td>
                <td>{{p.item_name}}</td>
                <td>{{p.purchase_qty}}</td>
                <td>{{p.purchase_price}}</td>
                <td>{{p.logistic}}</td>
                <td>{{p.total_purchase_price}}</td>
                <td><a href="{% url 'myapp:PurchaseDataDelete' p.id %}" class="btn btn-sm btn-danger"><i class="icon-copy bi bi-trash"></i></a></td>

            </tr>
            {% endfor %}



            </tbody>
            <tfoot>
            <tr>
                <td></td>
                <td></td>
                <th>TOTAL</th>
                <th>{{sum_purchase_qty}}</th>
                <th>{{sum_purchase_price}}</th>
                <th>{{sum_logistic}}</th>
                <th>{{sum_purchase_total}}</th>
                <th></th>
            </tr>
            </tfoot>
        </table>
    </div>
</div>
<!-- Export Datatable End -->
{% endblock content %}

pos/templates/statuschange.html
{% extends 'base.html' %}

{% block content %}
<!--filter form-->
<div class="pd-20 card-box mb-30">
    <div class="clearfix">
        <div class="pull-left">

        </div>
    </div>
    <form action="" method="post">{% csrf_token %}
        <div class="row">

            {{form}}
<button
                type="submit"
                class="btn btn-sm"
                data-bgcolor="#00b489"
                data-color="#ffffff"
        >
            Change Status

        </button>

        </div>

        <div>
            {% if message %}
            <hr>
        <a href="{{current_path}}" class="text-danger">{{message}}</a>
        {% endif %}
        </div>


    </form>
</div>


{% endblock content %}

pos/templates/supplier.html
{% extends 'base.html' %}

{% block content %}

<div class="page-header">
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h5>Create New Supplier</h5>

            </div>
            <hr>
            {% if message %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {% endif %}
            {% if success %}
            <div class="alert alert-success" role="alert">
                {{success}}
            </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <form action="{% url 'myapp:SupplierCreate' %}" method="post">{% csrf_token %}
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Supplier Name</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="supplier_name">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Phone Number</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="phone_number">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Address</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="address">
                    </div>
                </div>


                <input type="submit" value="Create Supplier" class="btn btn-outline-primary">


            </form>
        </div>
    </div>
</div>


<!--=============================================================-->
<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Supplier List</h4>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-warning">

                <th class="text-center">Supplier Name</th>
                <th class="text-center">Phone Number</th>
                <th class="text-center">Address</th>
<!--                <th>Vou</th>-->


            </tr>
            </thead>
            <tbody>
            {% for p in supplier %}
            <tr class="table-info">
                <td class="table-plus text-center"><a href="{% url 'myapp:SupplierEdit' p.id %}"><b>{{p.supplier_name}}</b></a></td>
                <td>{{p.phone_number}}</td>
                <td>{{p.address}}</td>
<!--                <td><a href="{% url 'myapp:PurchaseCreateView' p.id%}">Vouch</a></td>-->

            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

pos/templates/supplieredit.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header">
    <div class="row">
        <div class="col-md-12 col-sm-12">

            <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
                {{form}}
                <hr>
                <input type="submit" class="btn btn-primary" value="Save Product">
            </form>


        </div>

    </div>
</div>


{% endblock content %}